project:
  type: website
  execute-dir: project
  output-dir: docs

execute:
  freeze: auto

website:
  title: "NCEAS SciComp Workshop - Coding in the Tidyverse"
  favicon: images/scicomptools_hex.png
  repo-url: https://github.com/lter/workshop-tidyverse
  repo-actions: [issue]
  twitter-card: true
  sidebar:
    style: "docked"
    background: secondary
    collapse-level: 2
    search: true
    contents: 
      - text: "Workshop Home"
        href: index.qmd
      - section: "Modules"
        contents: 
         - href: wrangle.qmd
         - href: summarize.qmd
         - href: reshape.qmd
         - href: join.qmd
         - href: visualize.qmd
  navbar:
    background: primary
    right:
      - text: "SciComp Team"
        menu:
          - href: https://lter.github.io/scicomp/
            text: "Home"
          - href: https://lter.github.io/scicomp/staff.html
            text: "People"
      - icon: github
        href: https://github.com/lter/workshop-tidyverse
  page-footer:
    center: "Copyright 2024, LTER Network Office"
    background: secondary
  margin-footer: |
    <img src="images/logos/logo_nceas.png" alt="Logo for the National Center for Ecological Analysis and Synthesis (NCEAS)" width="40%"/>
    <img src="images/logos/logo_lter.png" alt="Logo for the Long Term Ecological Research (LTER) Network" width="40%"/>

format:
  html:
    theme:
       light: _extensions/lter/lter_scss-theme/theme_lter-edu-light.scss
       dark: _extensions/lter/lter_scss-theme/theme_lter-edu-dark.scss
    mainfont: Lato
    toc: true
    link-external-newwindow: true
    link-external-icon: false
