project:
  type: website
  execute-dir: project
  output-dir: docs

execute:
  freeze: auto

website:
  title: "NCEAS SciComp Workshop - Coding in the Tidyverse"
  favicon: images/scicomptools_hex.png
  repo-url: https://github.com/lter/workshop-tidyverse
  repo-actions: [issue]
  twitter-card: true
  sidebar:
    style: "docked"
    background: secondary
    search: true
    contents: 
      - text: "Workshop Home"
        href: index.qmd
      - wrangle.qmd
      - summarize.qmd
      - reshape.qmd
      - join.qmd
      - visualize.qmd
  navbar:
    background: primary
    right:
      - text: "SciComp Team"
        menu:
          - href: https://lter.github.io/scicomp/
            text: "Home"
          - href: https://lter.github.io/scicomp/staff.html
            text: "People"
          - href: https://lter.github.io/scicomp/workshops.html
            text: "Other Workshops"
      - icon: github
        href: https://github.com/lter/workshop-tidyverse
  page-footer:
    center: "Copyright 2022, NCEAS"
    background: secondary
  margin-footer: |
    <img src="images/nceas_logo_square.png" width="40%"/>
    <img src="images/lter_logo_square.png" width="40%"/>

format:
  html:
    theme:
       light: _extensions/lter/lter_scss-theme/theme_lter-edu-light.scss
       dark: _extensions/lter/lter_scss-theme/theme_lter-edu-dark.scss
    mainfont: Lato
    toc: true
    link-external-newwindow: true
    link-external-icon: false
